### ISSUE TITLE
Makefile and .m / .mm files

### ISSUE THREAD

**Issue by Daandelange** [atduskgreg/ofxUVC#9]
Hey,

I'm trying to compile ofxUVC using makefiles on osx, but .mm files are not included when scanning the /src folder throwing "method not implemented" errors. The same thing happens when compiling with qt-creator.

Renaming the .m and .mm to .cpp fixes the issue, so I'd like to know if you need these files to be named like that (?)

**Comment by atduskgreg** [comment]
The .m file is a Obj-C file. And the .mm file mixes c++ and Obj-C. I don't know exactly what your build chain is doing but the fact that naming an obj-c file with the .cpp extension makes it compile correctly sounds sketchy. And probably means you can make it work with the .m and .mm extensions which are correct and necessary for xcode.

**Comment by Daandelange** [comment]
OK, thanks. Going to investigate this on the OF side :)
